# Generated by Django 4.2.5 on 2023-10-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppBlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=models.CharField(max_length=1200),
        ),
    ]
